//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HakatonProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hakaton_projectEntities : DbContext
    {
        public Hakaton_projectEntities()
            : base("name=Hakaton_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<buildings> buildings { get; set; }
        public virtual DbSet<LocType> LocType { get; set; }
        public virtual DbSet<ResourseLocation> ResourseLocation { get; set; }
        public virtual DbSet<Resourses> Resourses { get; set; }
        public virtual DbSet<ResourseTypes> ResourseTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
