//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HakatonProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resourses
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public int ResourseType { get; set; }
        public int status { get; set; }
        public int location { get; set; }
    
        public virtual ResourseLocation ResourseLocation { get; set; }
        public virtual ResourseTypes ResourseTypes { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
